/* Generated by dia/codegen.py
 *
 * Generated files:
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Slot.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Inputpopup.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Asignatura.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Passinfodata.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Seleccionable.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Controlador.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Eventocreacionobjeto.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Docente.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Intervalotiempo .java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Persona.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Areatrabajo.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Interfazprincipal.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Usuariocancel.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Valoresfueradelrango.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Infopanel.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Alumno.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Nohaytiempo.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Grupoalumnos.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Habitacion.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Listatarjetas.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Conecxiones.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Seleccion.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Horario.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Controaldorbd.java
 *	/home/adrian/github/DAM/ProyectoDAM_Easy_Timetable/src/Controladorinterfaz.java
 */
